name: Minishell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y valgrind libreadline-dev

    - name: Compile the project
      run: make

    - name: Run valgrind check (simple test)
      run: |
        echo "exit" | valgrind --leak-check=full --show-leak-kinds=all ./minishell
